services:
  db:
    container_name: blog-postgres-db
    image: postgres:14.1
    environment:
      POSTGRES_USER: loctran
      POSTGRES_PASSWORD: Loc123456
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  blog-server:
    container_name: blog-server
    image: loctran070699/server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
    ports:
      - "4000:4000"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db: