server:
  port: 4000
#  servlet:
#    context-path: /api/v1
  error:
    include-message: always
    whitelabel:
      enabled: false
    path: /error
spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql:postgres:5432/blog
    username: loctran
    password: Loc123456

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
      format-sql: true
    show-sql: true

    logging.level:
      org.springframework.security: TRACE

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 50MB
      max-request-size: 100MB

application:
  security:
    jwt:
      secret-key: PJC7HnliwcxXw4FM8Ep3sX9NIL3R5CZnDvp8IyyCSlg=
      expiration: 3600000
      refresh-token:
        expiration: 86400000
        name: refreshToken
  bucket:
    name: tpl-blogger-bucket

