name: CI - Build backend

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15.3
        # Provide the password for postgres
        env:
          POSTGRES_USER: loctran
          POSTGRES_PASSWORD: Loc123456
          POSTGRES_DB: blog
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify