name: CI - Build backend

on:
  pull_request:
    branches:
      - main
    paths:
      - server/**

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: loctran
          POSTGRES_PASSWORD: Loc123456
          POSTGRES_DB: blog
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    defaults:
      run:
        working-directory: server
    steps:
      - name: Set up environment variables
        run: echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.2
      - name: Build and run Unit/Integration Tests with Maven
        run: mvn -ntp -B verify
